language: python
python:
    - '3.5'

sudo: false
cache: pip

install:
    - pip install pip --upgrade
    - pip install -r doc_requirements.txt
    - pip install flake8

before_script:
    - flake8 secuml
    - flake8 scripts

script:
    - sphinx-build -nWT docs/ docs/_build/html

deploy:
    provider: pages
    target-branch: gh-pages
    local-dir: docs/_build/html
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
